[package]
name = "vevy_bello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.16" 
bevy = { workspace = true }
vello = { workspace = true }
